### PR TITLE
Improvement to resolve system property placeholders

### PR DESCRIPTION
**Pull request by daneshk**
This improvement is to resolve system property in the value of any properties mentioned in the pax-logging.properties file. 

With this Fix, system will resolve the system properties mentioned within the value of the properties mentioned in the pax-logging.properties file. e.g:
````
org.ops4j.pax.logging.log4j2.config.file=${custom.home}/conf/log4j2.xml
````
Please review
Thanks
Danesh

### CODE REVIEW

**Comment by jvz** [comment]
Code looks fine, though there is a StrSubstitutor API in log4j2 already that you could use in theory. Can you also file an issue in jira so we have something in the changelog? Unit tests would be nice, too.

**Comment by daneshk** [comment]
@jvz Thanks for the suggestions. I made the changes to use StrSubstitutor API in log4j2 and removed system property read logic. Please review.
JIRA issue: https://ops4j1.jira.com/browse/PAXLOGGING-236

**Comment by daneshk** [comment]
Can you please review the fix and merge the PR. It would be great, if you can add this improvement in the next release.

**Comment by jvz** [comment]
Normally, we invite contributors to the ops4j organization so they can merge the code themselves and contribute more easily in the future. I don't know how to do that, but I'm sure someone can handle it. @ANierbeck ?

**Comment by jvz** [comment]
Oh, and your updates look good. Thanks for the PR!

**Comment by ANierbeck** [comment]
daneshk I just invited you to the team, welcome aboard.

**Comment by daneshk** [comment]
@jvz @ANierbeck Thanks for the quick response. Happy to be a part of the team :). I will proceed and merge the PR.

**Pull request merged**
