### PR TITLE
[Fixes #459] Include JsonTemplateLayout for log4j2

### LINKED ISSUE #459: Wrap log4j JsonTemplateLayout in pax-logging-log4j2
We just have to include a new log4j artifact in the wrapping (no additional dependency should be required).

### PR DESCRIPTION
**Pull request by svogt**
Signed-off-by: Sascha Vogt <sascha@vogt-neuenbuerg.de>

### CODE REVIEW

**Comment by svogt** [comment]
Figure out how to merge Log4j2Plugins.dat

**Comment by svogt** [comment]
With ugly workaround, it now works :) Was able to get Json output without further changes other than specifying an appropriate appender config

**Comment by prestongilchrist** [comment]
We are eager to see this change released.  Can you tell us
1. when this will be released?
2. Which versions it will be released in (2.x, 1.11.x)?

Thank you.

**Comment by grgrzybek** [comment]
for now, #459 is fixed in the main branch and it's targeted to version 2.1.1.
I see no problems adding it to 2.0.x branch (I even should do it - thanks for reminder).
I can also do it in 1.11.x/1.12.x - just let me know.

**Comment by grgrzybek** [comment]
Backports:
* to 2.0.x: #472
* to 1.12.x: #473
* to 1.11.x: #474

**Pull request merged**
