### PR TITLE
[PAXLOGGING-207] Upgrade to slf4j 1.7.13

### PR DESCRIPTION
**Pull request by duponter**
I have prepared an upgrade for the SLF4J library. Also, a JIRA issue has been created: https://ops4j1.jira.com/browse/PAXLOGGING-207

First, I have replaced to old source code with the one from slf4j-api version 1.7.13.
Next, I have exported the latest version (1.7.13) of the relevant packages.
However, locally the test run fails... can you look into this? Or which procedures do I have to follow to make them run (maybe activating some profiles)?

### CODE REVIEW

**Comment by jbonofre** [comment]
As I managed most of slf4j update, let me take a look ;)

**Comment by gnodet** [comment]
I don't think we need to export the same package in multiple minor versions, i.e. exporting 1.4.x, 1.5.x, 1.6.x, 1.7.x could be fine, but exporting 1.7.x and 1.7.y is quite useless imho.  Bundles usually import up to the next major version, and quite rarely up to the next minor version, but there's no reason to import [1.4,1.5) only.

**Comment by jbonofre** [comment]
It sounds like some bundles have import with a specific minor version (like 1.7.13).

**Comment by duponter** [comment]
I have added following comment to the related issue in JIRA:
https://ops4j1.jira.com/browse/PAXLOGGING-207?focusedCommentId=30742&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-30742

**Comment by jbonofre** [comment]
Thanks for the update. No rush so.

**Pull request closed without merging**
