### PR TITLE
Fixing logs missing issue due to asynchronous behaviour of the Config…

### PR DESCRIPTION
**Pull request by jsdjayanga**
…uration update

### CODE REVIEW

**Comment by ANierbeck** [comment]
Hi please open an issue at the ops4j issue tracker and link this PR with the issue, this is needed so we can track via the release notes, when which changes took an effect. 

Thanks, Achim

**Comment by jsdjayanga** [comment]
Hi,

As self-registration feature is disabled in Jira, I am unable to create a Jira ticket (How to get access to the Jira?). 
There is a discussion, I started on google groups with subject [2] to discuss this matter.

[1] "Some logs are missing when the Configuration is updated via ConfigurationAdmin"

Thanks,
Jayanga

**Comment by ANierbeck** [comment]
added you to the jira users. sorry about that inconvenience, but we've been swamped with spam via comments :(

**Comment by jsdjayanga** [comment]
Create the Jira ticket
https://ops4j1.jira.com/browse/PAXLOGGING-217

**Pull request merged**
