### PR TITLE
Init of PAXContext at bundle activation for Log4J2ThreadContext

### PR DESCRIPTION
**Pull request by GuillaumeKLECH**
This is my first pull request so sorry if i'm inadvertently doing something wrong...

I tried to fix the Log4J2ThreadContext so that i can use Log4J2 ThreadContext API without using PaxContext directly.

The problem was that the context was cleansed after each log.

### CODE REVIEW

**Comment by ANierbeck** [comment]
Hi, 
we usually track such changes with a corresponding Issue in our Jira system. 
Could you please open a corresponding ticket there? 
If you need access to it, give me a ping.

**Comment by GuillaumeKLECH** [comment]
OK i asked to have access to the jira [here](https://groups.google.com/forum/#!topic/ops4j/djvARNE8Q38).

**Comment by ANierbeck** [comment]
perfect, access is on it's way :)

**Comment by grgrzybek** [comment]
Closing as fixed with https://ops4j1.jira.com/browse/PAXLOGGING-244.

**Pull request closed without merging**
