### PR TITLE
Add support for triggering log4j2's composite behaviour

### PR DESCRIPTION
**Pull request by jamie-kemp**

### CODE REVIEW

**Comment by jamie-kemp** [comment]
Hi @tonit. By composite behaviour I mean the functionality described [here|https://logging.apache.org/log4j/2.x/manual/configuration.html#CompositeConfiguration]. Effectively the ability to have multiple unique configurations which log4j2 binds into a single configuration.

I will have a look at implementing a test case for this change.

**Comment by jbonofre** [comment]
@jamie-kemp can you please rebase and fix the conflict ?

**Comment by grgrzybek** [comment]
I have created https://ops4j1.jira.com/browse/PAXLOGGING-308 issue to allow running pax-logging entirely without ConfigurationAdmin. I'll reuse the idea (i.e., `log4j.configurationFile` property), but I'll do it for 3 backends.

**Comment by grgrzybek** [comment]
Here's new documentation about how to use external (not related to Configuration Admin) configuration (including your @jamie-kemp suggestion on composite Log4j2 configuration): https://ops4j1.jira.com/wiki/spaces/paxlogging/pages/499286109/Configuration#What-of-Configuration-Admin-is-not-available-at-all%3F

**Pull request closed without merging**
