### PR TITLE
Forward throwables in logback PaxLoggerImpl to doLog

### PR DESCRIPTION
**Pull request by aclemons**
It looks like this was accidentally introduced by d41b7e67.

### CODE REVIEW

**Comment by aclemons** [comment]
I am using pax-logging-logback and currently missing stack traces in log output because of this.

**Comment by grgrzybek** [comment]
Great - thanks for the missing throwables!

**Comment by grgrzybek** [comment]
@aclemons would you like 2.0.6 release?

**Comment by aclemons** [comment]
Yes, a new release would be nice, thanks.

**Comment by grgrzybek** [comment]
Pax Logging 2.0.6 available in https://repo1.maven.org/maven2/org/ops4j/pax/logging/

**Pull request merged**
